name: Say hello

on:
  push:
    branches:
      - master
jobs:
  hello_world:
    runs-on: windows-2022
    steps:
      - name: Echo the message
        run: |
          echo "Hola giuli"
      - name: dime la fecha
        run: date